### ISSUE TITLE
引入了广告,好上架吗?公司没有广告业务

### ISSUE THREAD

**Issue by kedu** [DanielYK/DYDeviceInfo#2]

**Comment by DanielYK** [comment]
你好，你的意思是说你使用了IDFA,但是没有引入广告 ？ 麻烦你说的稍微详细些

**Comment by kedu** [comment]
其实我是说我想拿广告标识做唯一id来用,但是这肯定就引入了广告框架.但是我的app里面是不带广告的,会被拒吗?

**Comment by DanielYK** [comment]
不会，但是你再提交审核的时候要选择含有idfa，我之前做过一个APP，只是为了统计点击广告下载的应用数量。内部没有广告。上架成功。
